export const countryCodes: { code: string; name: string }[] = [
  { code: "+1", name: "United States" },
  { code: "+44", name: "United Kingdom" },
  { code: "+91", name: "India" },
  { code: "+86", name: "China" },
  { code: "+81", name: "Japan" },
  { code: "+49", name: "Germany" },
  { code: "+33", name: "France" },
  { code: "+61", name: "Australia" },
  { code: "+7", name: "Russia" },
  { code: "+82", name: "South Korea" },
  { code: "+34", name: "Spain" },
  { code: "+39", name: "Italy" },
  { code: "+55", name: "Brazil" },
  { code: "+51", name: "Peru" },
  { code: "+92", name: "Pakistan" },
  { code: "+880", name: "Bangladesh" },
  { code: "+62", name: "Indonesia" },
  { code: "+63", name: "Philippines" },
  { code: "+66", name: "Thailand" },
  { code: "+84", name: "Vietnam" },
];
